### ISSUE TITLE
SwaggerRequestExample always returns the same example

### ISSUE THREAD

**Issue by freeranger** [mattfrear/Swashbuckle.AspNetCore.Examples#19] opened 2017-11-06 05:47 UTC
Hi,

I have decorated different actions in different controllers with:
[SwaggerRequestExample(typeof(JsonPatchDocument), typeof(PatchTypeOneExample))]

and
[SwaggerRequestExample(typeof(JsonPatchDocument), typeof(PatchTypeTwoExample))]

ie, the input type is the same - JsonPatchDocument, but the example values are quite different, because they are patching different types of resources.

In my swagger docs though I am seeing the PatchTypeOneExample for both.
Is this a bug in the code, or is there some way to override the behaviour?

thanks

**Comment by mattfrear** [comment] 2017-11-06 09:30
This sounds like a bug in my library - I usually have a different request object for every controller action so I haven't seen this behaviour. I'll investigate when I get a chance, but that may not be any time soon.

**Comment by freeranger** [comment] 2017-11-06 10:23
Yeah, I do for every other case too, but we are supporting PATCH operations now on collections and they just take a JsonPatchDocument, but of course the content is completely different for different types of resource, so I need different examples in each case.

thanks

**Comment by freeranger** [comment] 2017-11-06 13:58
@mattfrear looking at your code:
```
var parts = schema.Ref?.Split('/');
var name = parts.Last();
if (schemaRegistry.Definitions.ContainsKey(name))
{
    var definitionToUpdate = schemaRegistry.Definitions[name];
    var serializerSettings = SerializerSettings(attr.ContractResolver, attr.JsonConverter);
    definitionToUpdate.Example = FormatJson(provider, serializerSettings, false);
 }
```
The "name" here is "JsonPatchDocument", which is correct.
And then you update the definition of that type to add the example.....so that isn't a bug in your code, right?  It's doing what it should.

What I mean is, I am providing an example for the schema type "JsonPatchDocument" and you are updating the definition of JsonPatchDocument to include that example, which would seem to be entirely correct.....so now what?

I don't know enough about the swagger format to know if this is correct according to that - perhaps there is no way to provide different examples for the same type, depending on their usage.

The only thing I can think of at the moment, which feels hacky, is to create subclasses of JsonPatchDocument, one per example I need, just for the purposes of this documentation - it would add no new properties or anything to JsonPatchDocument.

Am I barking up the wrong tree here?

**Comment by mattfrear** [comment] 2017-11-06 14:15
Thanks for refreshing my memory. Yep, you're right. For requests there's only one schema defined and it only has one example object, so it's not a bug.

Changing your production code just for documentation wouldn't be ideal either... but then again, if you use subclasses you'll have a unique object for each request which, I think, is usually a good thing.

**Comment by freeranger** [comment] 2017-11-06 16:26
hmm...I'm not so sure that follows - I could have, say, a GET action on multiple controllers which take an int id - the "model" is an int in this case - I don't think that's any different to the model being an object in terms of it being a good thing or not.

Yeah looks like the "parameters" object has a single "schema" reference, which itself has a single example...so I guess I'm knackered then.
It seems strange to have this limitation - I can't imagine I am the only person to what to pass the same model type to different actions and therefore have different examples for each one....weird

**Comment by mattfrear** [comment] 2017-11-07 11:30
Closing, as this is a limitation of the swagger spec.

**Closed by mattfrear** 2017-11-07 11:30 UTC
